apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: user1-data
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

