apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressspaceplans.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: AddressSpacePlan
    listKind: AddressSpacePlanList
    singular: addressspaceplan
    plural: addressspaceplans
  versions:
    - name: v1beta1
      served: true
      storage: true
    - name: v1alpha1
      served: true
      storage: false
  validation:
    openAPIV3Schema:
      properties:
        displayName:
          type: string
        displayOrder:
          type: integer
        shortDescription:
          type: string
        longDescription:
          type: string
        uuid:
          type: string
        addressSpaceType:
          type: string
        resources:
          type: array
          items:
            type: object
            required:
            - name
            - max
            properties:
              name:
                type: string
              max:
                type: number
        addressPlans:
          type: array
          items:
            type: string
