iot:
  frequency: 5
  types: motor-temperature,vibration

pump:
  devices: 1,2

mqtt:
  username: iotuser
  password: iotuser
  service: localhost
  port: 1883

app:
  # log_manager_<student_number>
  name: "log_manager_123"
