iot:
  frequency: 5
  types: temperature

pump:
  devices: 1

mqtt:
  username: device1
  password: password
  service: mqtt-hep7ux89ck-messaging.apps.cluster-80a2.80a2.openshiftworkshop.com
  port: 443

app:
  # log_manager_<user namespace>
  name: "log_manager_user1"
