iot:
  frequency: 5
  types: temperature,vibration

pump:
  devices: 1,2,3,4,5,6,7,8

mqtt:
  username: device1
  password: password
  service: replaceme.svc
  port: 443

app:
  name: user1
amq.topic: ${app.name}
stomp.queue: sensordata
amqphub.amqp10jms:
  remote-url: amqp://${MESSAGING_SERVICE}:${MESSAGING_PORT}?amqp.saslMechanisms=PLAIN
  username: ${MESSAGING_USERNAME}
  password: ${MESSAGING_PASSWORD}
  pool:
    useAnonymousProducers: false
    enabled: true
