iot:
  frequency: 5
  types: temperature,vibration

pump:
  devices: 1,2

mqtt:
  username: device
  password: ''
  service: mqtt-hep7ux89ck-messaging.apps.cluster-80a2.80a2.openshiftworkshop.com
  port: 443

app:
  # log_manager_<user namespace>
  name: "log_manager_user1"
