mqtt:
  username: device1
  password: password
  service: localhost
  port: 61616

pump:
  devices: 1

amqphub:
  amqp10jms:
    remote-url: amqp://localhost:61616?amqp.saslMechanisms=PLAIN
    username: device1
    password: password
