iot:
  frequency: 5
  types: temperature

pump:
  devices: 1,2

mqtt:
  username: device1
  password: password
  service: replaceme.svc
  port: 443

app:
  # log_manager_<user namespace>
  name: "log_manager_user1"
