mqtt:
  username: device1
  password: password
  service: localhost
  port: 61616

pump:
  devices: 1
iot:
  types: temperature

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: device1
    password: password
