kind: Template
apiVersion: v1
metadata:
  annotations:
    version: "1.0"
    openshift.io/display-name: lab-manager
  name: lab-manager
labels:
  template: lab-manager
message: |-
  AddressSpace provisioned
parameters:
  - name: APPLICATION_NAME
    value: lab-manager
    required: true
  - name: APPLICATION_NAMESPACE
    required: true
objects:
#  - apiVersion: enmasse.io/v1beta1
#    kind: AddressSpace
#    metadata:
#      name: ${APPLICATION_NAMESPACE}
#    spec:
#      type: brokered
#      plan: brokered-single-broker
#      authenticationService:
#        type: standard
#      endpoints:
#        - name: mqtt
#          service: mqtt
#          expose:
#            type: loadbalancer
#            loadBalancerPorts:
#              - mqtt
#          cert:
#            provider: openshift
  - apiVersion: enmasse.io/v1beta1
    kind: AddressSpace
    metadata:
      name: ${APPLICATION_NAMESPACE}
    spec:
      type: standard
      plan: standard-unlimited
