kind: Template
apiVersion: v1
metadata:
  annotations:
    version: "1.0"
    openshift.io/display-name: lab-manager
  name: lab-manager
labels:
  template: labe-manager
message: |-
  AddressSpace provisioned
parameters:
  - name: APPLICATION_NAME
    value: lab-manager
    required: true
  - name: APPLICATION_NAMESPACE
    required: true
objects:
  - apiVersion: enmasse.io/v1beta1
    kind: Address
    metadata:
      name: "${APPLICATION_NAMESPACE}.temperature"
      labels:
        application: "${APPLICATION_NAME}"
        service: "${APPLICATION_NAME}"
    spec:
      address: temperature
      type: topic
      plan: brokered-topic
