kind: List
apiVersion: v1
metadata:
  name: amq-streams-console
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: strimzi-console-server
    labels:
      app: strimzi
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: strimzi-console-server
      spec:
        containers:
        - name: strimzi-console-server
          image: quay.io/redhatdemo/console-server:latest
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: hack-cluster-kafka-bootstrap:9092
          - name: STRIMZI_LOG_LEVEL
            value: INFO
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 512Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    name: strimzi-console-server
    labels:
      name: strimzi-console-server
      app: strimzi
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: http
    selector:
      name: strimzi-console-server
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: strimzi-console
    labels:
      app: strimzi
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: strimzi-console
      spec:
        containers:
        - name: strimzi-console
          image: quay.io/redhatdemo/console-pages:latest
          ports:
            - name: http
              containerPort: 8888
          resources:
            requests:
              memory: 256Mi
              cpu: "0.1"
            limits:
              memory: 256Mi
              cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    name: strimzi-console
    labels:
      name: strimzi-console
      app: strimzi
  spec:
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
    selector:
      name: strimzi-console