apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: cluster-name
  name: topic-name
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3