apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default-with-mqtt
  labels:
    app: enmasse
  annotations:
    enmasse.io/with-mqtt: "true"
spec:
  version: "0.26"
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
